/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Accommodation {
  'pricePerNight' : number,
  'name' : string,
  'type' : AccommodationType,
  'location' : string,
}
export type AccommodationType = { 'hotel' : null } |
  { 'other' : null } |
  { 'apartment' : null } |
  { 'hostel' : null };
export interface BudgetEstimate {
  'total' : number,
  'food' : number,
  'transport' : number,
  'stay' : number,
  'attractions' : number,
}
export interface CostAssumptions {
  'hotelLevel' : string,
  'dailyFoodBudget' : number,
  'transportType' : string,
}
export interface Currency {
  'code' : string,
  'exchangeRate' : number,
  'symbol' : string,
}
export interface EmergencyContact {
  'name' : string,
  'type' : string,
  'phone' : string,
}
export interface FoodRecommendation {
  'name' : string,
  'type' : FoodType,
  'description' : string,
  'budgetLevel' : string,
  'imageUrl' : [] | [string],
  'popularity' : bigint,
}
export type FoodType = { 'veg' : null } |
  { 'nonVeg' : null } |
  { 'other' : null };
export interface ItineraryDay { 'date' : Time, 'activities' : Array<string> }
export interface LocalTransportOption {
  'type' : TransportType,
  'currency' : Currency,
  'price' : number,
}
export interface MustVisitPlace {
  'name' : string,
  'type' : PlaceType,
  'description' : string,
}
export type PlaceType = { 'other' : null } |
  { 'cultural' : null } |
  { 'historical' : null } |
  { 'natural' : null };
export type Time = bigint;
export interface ToDo {
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'notes' : string,
}
export type TransportType = { 'metro' : null } |
  { 'train' : null } |
  { 'carRentals' : null } |
  { 'other' : null } |
  { 'publicBus' : null } |
  { 'bikeRentals' : null } |
  { 'taxi' : null } |
  { 'autoRikshaw' : null } |
  { 'taxiService' : null } |
  { 'ferry' : null };
export interface TripPlan {
  'id' : bigint,
  'title' : string,
  'destination' : string,
  'toDos' : Array<ToDo>,
  'endDate' : Time,
  'mustVisitPlaces' : Array<MustVisitPlace>,
  'foodRecommendations' : Array<FoodRecommendation>,
  'currency' : Currency,
  'accommodations' : Array<Accommodation>,
  'costAssumptions' : CostAssumptions,
  'emergencyInfo' : Array<EmergencyContact>,
  'localTransportOptions' : Array<LocalTransportOption>,
  'budget' : BudgetEstimate,
  'totalFoodBudget' : number,
  'itinerary' : Array<ItineraryDay>,
  'startDate' : Time,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccommodations' : ActorMethod<[bigint, Array<Accommodation>], undefined>,
  'addFoodRecommendations' : ActorMethod<
    [bigint, Array<FoodRecommendation>],
    undefined
  >,
  'addLocalTransportOptions' : ActorMethod<
    [bigint, Array<LocalTransportOption>],
    undefined
  >,
  'addMustVisitPlaces' : ActorMethod<
    [bigint, Array<MustVisitPlace>],
    undefined
  >,
  'addTripEmergencyInfo' : ActorMethod<
    [bigint, Array<EmergencyContact>],
    undefined
  >,
  'addTripToDos' : ActorMethod<[bigint, Array<ToDo>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'convertTripCurrenciesToInr' : ActorMethod<[bigint], undefined>,
  'createTripPlan' : ActorMethod<
    [
      string,
      string,
      Time,
      Time,
      Array<ItineraryDay>,
      BudgetEstimate,
      CostAssumptions,
      Currency,
      Array<Accommodation>,
      Array<MustVisitPlace>,
      Array<FoodRecommendation>,
      Array<LocalTransportOption>,
      number,
    ],
    bigint
  >,
  'deleteTripPlan' : ActorMethod<[bigint], undefined>,
  'getAllTripPlans' : ActorMethod<[], Array<TripPlan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInrCurrency' : ActorMethod<[], Currency>,
  'getTripPlan' : ActorMethod<[bigint], TripPlan>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markToDoCompleted' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBudgetEstimates' : ActorMethod<
    [bigint, BudgetEstimate, CostAssumptions],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];