/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AccommodationType = IDL.Variant({
  'hotel' : IDL.Null,
  'other' : IDL.Null,
  'apartment' : IDL.Null,
  'hostel' : IDL.Null,
});
export const Accommodation = IDL.Record({
  'pricePerNight' : IDL.Float64,
  'name' : IDL.Text,
  'type' : AccommodationType,
  'location' : IDL.Text,
});
export const FoodType = IDL.Variant({
  'veg' : IDL.Null,
  'nonVeg' : IDL.Null,
  'other' : IDL.Null,
});
export const FoodRecommendation = IDL.Record({
  'name' : IDL.Text,
  'type' : FoodType,
  'description' : IDL.Text,
  'budgetLevel' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'popularity' : IDL.Int,
});
export const TransportType = IDL.Variant({
  'metro' : IDL.Null,
  'train' : IDL.Null,
  'carRentals' : IDL.Null,
  'other' : IDL.Null,
  'publicBus' : IDL.Null,
  'bikeRentals' : IDL.Null,
  'taxi' : IDL.Null,
  'autoRikshaw' : IDL.Null,
  'taxiService' : IDL.Null,
  'ferry' : IDL.Null,
});
export const Currency = IDL.Record({
  'code' : IDL.Text,
  'exchangeRate' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const LocalTransportOption = IDL.Record({
  'type' : TransportType,
  'currency' : Currency,
  'price' : IDL.Float64,
});
export const PlaceType = IDL.Variant({
  'other' : IDL.Null,
  'cultural' : IDL.Null,
  'historical' : IDL.Null,
  'natural' : IDL.Null,
});
export const MustVisitPlace = IDL.Record({
  'name' : IDL.Text,
  'type' : PlaceType,
  'description' : IDL.Text,
});
export const EmergencyContact = IDL.Record({
  'name' : IDL.Text,
  'type' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const ToDo = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'notes' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ItineraryDay = IDL.Record({
  'date' : Time,
  'activities' : IDL.Vec(IDL.Text),
});
export const BudgetEstimate = IDL.Record({
  'total' : IDL.Float64,
  'food' : IDL.Float64,
  'transport' : IDL.Float64,
  'stay' : IDL.Float64,
  'attractions' : IDL.Float64,
});
export const CostAssumptions = IDL.Record({
  'hotelLevel' : IDL.Text,
  'dailyFoodBudget' : IDL.Float64,
  'transportType' : IDL.Text,
});
export const TripPlan = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'destination' : IDL.Text,
  'toDos' : IDL.Vec(ToDo),
  'endDate' : Time,
  'mustVisitPlaces' : IDL.Vec(MustVisitPlace),
  'foodRecommendations' : IDL.Vec(FoodRecommendation),
  'currency' : Currency,
  'accommodations' : IDL.Vec(Accommodation),
  'costAssumptions' : CostAssumptions,
  'emergencyInfo' : IDL.Vec(EmergencyContact),
  'localTransportOptions' : IDL.Vec(LocalTransportOption),
  'budget' : BudgetEstimate,
  'totalFoodBudget' : IDL.Float64,
  'itinerary' : IDL.Vec(ItineraryDay),
  'startDate' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccommodations' : IDL.Func([IDL.Nat, IDL.Vec(Accommodation)], [], []),
  'addFoodRecommendations' : IDL.Func(
      [IDL.Nat, IDL.Vec(FoodRecommendation)],
      [],
      [],
    ),
  'addLocalTransportOptions' : IDL.Func(
      [IDL.Nat, IDL.Vec(LocalTransportOption)],
      [],
      [],
    ),
  'addMustVisitPlaces' : IDL.Func([IDL.Nat, IDL.Vec(MustVisitPlace)], [], []),
  'addTripEmergencyInfo' : IDL.Func(
      [IDL.Nat, IDL.Vec(EmergencyContact)],
      [],
      [],
    ),
  'addTripToDos' : IDL.Func([IDL.Nat, IDL.Vec(ToDo)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'convertTripCurrenciesToInr' : IDL.Func([IDL.Nat], [], []),
  'createTripPlan' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        IDL.Vec(ItineraryDay),
        BudgetEstimate,
        CostAssumptions,
        Currency,
        IDL.Vec(Accommodation),
        IDL.Vec(MustVisitPlace),
        IDL.Vec(FoodRecommendation),
        IDL.Vec(LocalTransportOption),
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteTripPlan' : IDL.Func([IDL.Nat], [], []),
  'getAllTripPlans' : IDL.Func([], [IDL.Vec(TripPlan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInrCurrency' : IDL.Func([], [Currency], []),
  'getTripPlan' : IDL.Func([IDL.Nat], [TripPlan], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markToDoCompleted' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBudgetEstimates' : IDL.Func(
      [IDL.Nat, BudgetEstimate, CostAssumptions],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AccommodationType = IDL.Variant({
    'hotel' : IDL.Null,
    'other' : IDL.Null,
    'apartment' : IDL.Null,
    'hostel' : IDL.Null,
  });
  const Accommodation = IDL.Record({
    'pricePerNight' : IDL.Float64,
    'name' : IDL.Text,
    'type' : AccommodationType,
    'location' : IDL.Text,
  });
  const FoodType = IDL.Variant({
    'veg' : IDL.Null,
    'nonVeg' : IDL.Null,
    'other' : IDL.Null,
  });
  const FoodRecommendation = IDL.Record({
    'name' : IDL.Text,
    'type' : FoodType,
    'description' : IDL.Text,
    'budgetLevel' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'popularity' : IDL.Int,
  });
  const TransportType = IDL.Variant({
    'metro' : IDL.Null,
    'train' : IDL.Null,
    'carRentals' : IDL.Null,
    'other' : IDL.Null,
    'publicBus' : IDL.Null,
    'bikeRentals' : IDL.Null,
    'taxi' : IDL.Null,
    'autoRikshaw' : IDL.Null,
    'taxiService' : IDL.Null,
    'ferry' : IDL.Null,
  });
  const Currency = IDL.Record({
    'code' : IDL.Text,
    'exchangeRate' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const LocalTransportOption = IDL.Record({
    'type' : TransportType,
    'currency' : Currency,
    'price' : IDL.Float64,
  });
  const PlaceType = IDL.Variant({
    'other' : IDL.Null,
    'cultural' : IDL.Null,
    'historical' : IDL.Null,
    'natural' : IDL.Null,
  });
  const MustVisitPlace = IDL.Record({
    'name' : IDL.Text,
    'type' : PlaceType,
    'description' : IDL.Text,
  });
  const EmergencyContact = IDL.Record({
    'name' : IDL.Text,
    'type' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const ToDo = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'notes' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ItineraryDay = IDL.Record({
    'date' : Time,
    'activities' : IDL.Vec(IDL.Text),
  });
  const BudgetEstimate = IDL.Record({
    'total' : IDL.Float64,
    'food' : IDL.Float64,
    'transport' : IDL.Float64,
    'stay' : IDL.Float64,
    'attractions' : IDL.Float64,
  });
  const CostAssumptions = IDL.Record({
    'hotelLevel' : IDL.Text,
    'dailyFoodBudget' : IDL.Float64,
    'transportType' : IDL.Text,
  });
  const TripPlan = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'destination' : IDL.Text,
    'toDos' : IDL.Vec(ToDo),
    'endDate' : Time,
    'mustVisitPlaces' : IDL.Vec(MustVisitPlace),
    'foodRecommendations' : IDL.Vec(FoodRecommendation),
    'currency' : Currency,
    'accommodations' : IDL.Vec(Accommodation),
    'costAssumptions' : CostAssumptions,
    'emergencyInfo' : IDL.Vec(EmergencyContact),
    'localTransportOptions' : IDL.Vec(LocalTransportOption),
    'budget' : BudgetEstimate,
    'totalFoodBudget' : IDL.Float64,
    'itinerary' : IDL.Vec(ItineraryDay),
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccommodations' : IDL.Func([IDL.Nat, IDL.Vec(Accommodation)], [], []),
    'addFoodRecommendations' : IDL.Func(
        [IDL.Nat, IDL.Vec(FoodRecommendation)],
        [],
        [],
      ),
    'addLocalTransportOptions' : IDL.Func(
        [IDL.Nat, IDL.Vec(LocalTransportOption)],
        [],
        [],
      ),
    'addMustVisitPlaces' : IDL.Func([IDL.Nat, IDL.Vec(MustVisitPlace)], [], []),
    'addTripEmergencyInfo' : IDL.Func(
        [IDL.Nat, IDL.Vec(EmergencyContact)],
        [],
        [],
      ),
    'addTripToDos' : IDL.Func([IDL.Nat, IDL.Vec(ToDo)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'convertTripCurrenciesToInr' : IDL.Func([IDL.Nat], [], []),
    'createTripPlan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          IDL.Vec(ItineraryDay),
          BudgetEstimate,
          CostAssumptions,
          Currency,
          IDL.Vec(Accommodation),
          IDL.Vec(MustVisitPlace),
          IDL.Vec(FoodRecommendation),
          IDL.Vec(LocalTransportOption),
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteTripPlan' : IDL.Func([IDL.Nat], [], []),
    'getAllTripPlans' : IDL.Func([], [IDL.Vec(TripPlan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInrCurrency' : IDL.Func([], [Currency], []),
    'getTripPlan' : IDL.Func([IDL.Nat], [TripPlan], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markToDoCompleted' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBudgetEstimates' : IDL.Func(
        [IDL.Nat, BudgetEstimate, CostAssumptions],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };