/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CostAssumptions {
    hotelLevel: string;
    dailyFoodBudget: number;
    transportType: string;
}
export interface MustVisitPlace {
    name: string;
    type: PlaceType;
    description: string;
}
export type Time = bigint;
export interface LocalTransportOption {
    type: TransportType;
    currency: Currency;
    price: number;
}
export interface EmergencyContact {
    name: string;
    type: string;
    phone: string;
}
export interface Currency {
    code: string;
    exchangeRate: number;
    symbol: string;
}
export interface BudgetEstimate {
    total: number;
    food: number;
    transport: number;
    stay: number;
    attractions: number;
}
export interface TripPlan {
    id: bigint;
    title: string;
    destination: string;
    toDos: Array<ToDo>;
    endDate: Time;
    mustVisitPlaces: Array<MustVisitPlace>;
    foodRecommendations: Array<FoodRecommendation>;
    currency: Currency;
    accommodations: Array<Accommodation>;
    costAssumptions: CostAssumptions;
    emergencyInfo: Array<EmergencyContact>;
    localTransportOptions: Array<LocalTransportOption>;
    budget: BudgetEstimate;
    totalFoodBudget: number;
    itinerary: Array<ItineraryDay>;
    startDate: Time;
}
export interface FoodRecommendation {
    name: string;
    type: FoodType;
    description: string;
    budgetLevel: string;
    imageUrl?: string;
    popularity: bigint;
}
export interface ItineraryDay {
    date: Time;
    activities: Array<string>;
}
export interface Accommodation {
    pricePerNight: number;
    name: string;
    type: AccommodationType;
    location: string;
}
export interface ToDo {
    title: string;
    completed: boolean;
    dueDate?: Time;
    notes: string;
}
export interface UserProfile {
    name: string;
}
export enum AccommodationType {
    hotel = "hotel",
    other = "other",
    apartment = "apartment",
    hostel = "hostel"
}
export enum FoodType {
    veg = "veg",
    nonVeg = "nonVeg",
    other = "other"
}
export enum PlaceType {
    other = "other",
    cultural = "cultural",
    historical = "historical",
    natural = "natural"
}
export enum TransportType {
    metro = "metro",
    train = "train",
    carRentals = "carRentals",
    other = "other",
    publicBus = "publicBus",
    bikeRentals = "bikeRentals",
    taxi = "taxi",
    autoRikshaw = "autoRikshaw",
    taxiService = "taxiService",
    ferry = "ferry"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAccommodations(tripId: bigint, accommodations: Array<Accommodation>): Promise<void>;
    addFoodRecommendations(tripId: bigint, recommendations: Array<FoodRecommendation>): Promise<void>;
    addLocalTransportOptions(tripId: bigint, options: Array<LocalTransportOption>): Promise<void>;
    addMustVisitPlaces(tripId: bigint, places: Array<MustVisitPlace>): Promise<void>;
    addTripEmergencyInfo(tripId: bigint, emergencyInfo: Array<EmergencyContact>): Promise<void>;
    addTripToDos(tripId: bigint, todos: Array<ToDo>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    convertTripCurrenciesToInr(tripId: bigint): Promise<void>;
    createTripPlan(title: string, destination: string, startDate: Time, endDate: Time, itinerary: Array<ItineraryDay>, budget: BudgetEstimate, costAssumptions: CostAssumptions, currency: Currency, accommodations: Array<Accommodation>, mustVisitPlaces: Array<MustVisitPlace>, foodRecommendations: Array<FoodRecommendation>, localTransportOptions: Array<LocalTransportOption>, totalFoodBudget: number): Promise<bigint>;
    deleteTripPlan(tripId: bigint): Promise<void>;
    getAllTripPlans(): Promise<Array<TripPlan>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInrCurrency(): Promise<Currency>;
    getTripPlan(tripId: bigint): Promise<TripPlan>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markToDoCompleted(tripId: bigint, toDoIndex: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBudgetEstimates(tripId: bigint, budget: BudgetEstimate, costAssumptions: CostAssumptions): Promise<void>;
}
import type { Accommodation as _Accommodation, AccommodationType as _AccommodationType, BudgetEstimate as _BudgetEstimate, CostAssumptions as _CostAssumptions, Currency as _Currency, EmergencyContact as _EmergencyContact, FoodRecommendation as _FoodRecommendation, FoodType as _FoodType, ItineraryDay as _ItineraryDay, LocalTransportOption as _LocalTransportOption, MustVisitPlace as _MustVisitPlace, PlaceType as _PlaceType, Time as _Time, ToDo as _ToDo, TransportType as _TransportType, TripPlan as _TripPlan, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAccommodations(arg0: bigint, arg1: Array<Accommodation>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccommodations(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccommodations(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addFoodRecommendations(arg0: bigint, arg1: Array<FoodRecommendation>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFoodRecommendations(arg0, to_candid_vec_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFoodRecommendations(arg0, to_candid_vec_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addLocalTransportOptions(arg0: bigint, arg1: Array<LocalTransportOption>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocalTransportOptions(arg0, to_candid_vec_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLocalTransportOptions(arg0, to_candid_vec_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addMustVisitPlaces(arg0: bigint, arg1: Array<MustVisitPlace>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMustVisitPlaces(arg0, to_candid_vec_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMustVisitPlaces(arg0, to_candid_vec_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addTripEmergencyInfo(arg0: bigint, arg1: Array<EmergencyContact>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTripEmergencyInfo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTripEmergencyInfo(arg0, arg1);
            return result;
        }
    }
    async addTripToDos(arg0: bigint, arg1: Array<ToDo>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTripToDos(arg0, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTripToDos(arg0, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async convertTripCurrenciesToInr(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.convertTripCurrenciesToInr(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertTripCurrenciesToInr(arg0);
            return result;
        }
    }
    async createTripPlan(arg0: string, arg1: string, arg2: Time, arg3: Time, arg4: Array<ItineraryDay>, arg5: BudgetEstimate, arg6: CostAssumptions, arg7: Currency, arg8: Array<Accommodation>, arg9: Array<MustVisitPlace>, arg10: Array<FoodRecommendation>, arg11: Array<LocalTransportOption>, arg12: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTripPlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg8), to_candid_vec_n16(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n6(this._uploadFile, this._downloadFile, arg10), to_candid_vec_n11(this._uploadFile, this._downloadFile, arg11), arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTripPlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg8), to_candid_vec_n16(this._uploadFile, this._downloadFile, arg9), to_candid_vec_n6(this._uploadFile, this._downloadFile, arg10), to_candid_vec_n11(this._uploadFile, this._downloadFile, arg11), arg12);
            return result;
        }
    }
    async deleteTripPlan(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTripPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTripPlan(arg0);
            return result;
        }
    }
    async getAllTripPlans(): Promise<Array<TripPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTripPlans();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTripPlans();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInrCurrency(): Promise<Currency> {
        if (this.processError) {
            try {
                const result = await this.actor.getInrCurrency();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInrCurrency();
            return result;
        }
    }
    async getTripPlan(arg0: bigint): Promise<TripPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripPlan(arg0);
                return from_candid_TripPlan_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripPlan(arg0);
            return from_candid_TripPlan_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markToDoCompleted(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markToDoCompleted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markToDoCompleted(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBudgetEstimates(arg0: bigint, arg1: BudgetEstimate, arg2: CostAssumptions): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudgetEstimates(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudgetEstimates(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AccommodationType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccommodationType): AccommodationType {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Accommodation_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Accommodation): Accommodation {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_FoodRecommendation_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodRecommendation): FoodRecommendation {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_FoodType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodType): FoodType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_LocalTransportOption_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocalTransportOption): LocalTransportOption {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_MustVisitPlace_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MustVisitPlace): MustVisitPlace {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PlaceType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaceType): PlaceType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ToDo_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToDo): ToDo {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_TransportType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransportType): TransportType {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_TripPlan_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripPlan): TripPlan {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    destination: string;
    toDos: Array<_ToDo>;
    endDate: _Time;
    mustVisitPlaces: Array<_MustVisitPlace>;
    foodRecommendations: Array<_FoodRecommendation>;
    currency: _Currency;
    accommodations: Array<_Accommodation>;
    costAssumptions: _CostAssumptions;
    emergencyInfo: Array<_EmergencyContact>;
    localTransportOptions: Array<_LocalTransportOption>;
    budget: _BudgetEstimate;
    totalFoodBudget: number;
    itinerary: Array<_ItineraryDay>;
    startDate: _Time;
}): {
    id: bigint;
    title: string;
    destination: string;
    toDos: Array<ToDo>;
    endDate: Time;
    mustVisitPlaces: Array<MustVisitPlace>;
    foodRecommendations: Array<FoodRecommendation>;
    currency: Currency;
    accommodations: Array<Accommodation>;
    costAssumptions: CostAssumptions;
    emergencyInfo: Array<EmergencyContact>;
    localTransportOptions: Array<LocalTransportOption>;
    budget: BudgetEstimate;
    totalFoodBudget: number;
    itinerary: Array<ItineraryDay>;
    startDate: Time;
} {
    return {
        id: value.id,
        title: value.title,
        destination: value.destination,
        toDos: from_candid_vec_n29(_uploadFile, _downloadFile, value.toDos),
        endDate: value.endDate,
        mustVisitPlaces: from_candid_vec_n33(_uploadFile, _downloadFile, value.mustVisitPlaces),
        foodRecommendations: from_candid_vec_n38(_uploadFile, _downloadFile, value.foodRecommendations),
        currency: value.currency,
        accommodations: from_candid_vec_n44(_uploadFile, _downloadFile, value.accommodations),
        costAssumptions: value.costAssumptions,
        emergencyInfo: value.emergencyInfo,
        localTransportOptions: from_candid_vec_n49(_uploadFile, _downloadFile, value.localTransportOptions),
        budget: value.budget,
        totalFoodBudget: value.totalFoodBudget,
        itinerary: value.itinerary,
        startDate: value.startDate
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    completed: boolean;
    dueDate: [] | [_Time];
    notes: string;
}): {
    title: string;
    completed: boolean;
    dueDate?: Time;
    notes: string;
} {
    return {
        title: value.title,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.dueDate)),
        notes: value.notes
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    type: _PlaceType;
    description: string;
}): {
    name: string;
    type: PlaceType;
    description: string;
} {
    return {
        name: value.name,
        type: from_candid_PlaceType_n36(_uploadFile, _downloadFile, value.type),
        description: value.description
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    type: _FoodType;
    description: string;
    budgetLevel: string;
    imageUrl: [] | [string];
    popularity: bigint;
}): {
    name: string;
    type: FoodType;
    description: string;
    budgetLevel: string;
    imageUrl?: string;
    popularity: bigint;
} {
    return {
        name: value.name,
        type: from_candid_FoodType_n41(_uploadFile, _downloadFile, value.type),
        description: value.description,
        budgetLevel: value.budgetLevel,
        imageUrl: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.imageUrl)),
        popularity: value.popularity
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pricePerNight: number;
    name: string;
    type: _AccommodationType;
    location: string;
}): {
    pricePerNight: number;
    name: string;
    type: AccommodationType;
    location: string;
} {
    return {
        pricePerNight: value.pricePerNight,
        name: value.name,
        type: from_candid_AccommodationType_n47(_uploadFile, _downloadFile, value.type),
        location: value.location
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    type: _TransportType;
    currency: _Currency;
    price: number;
}): {
    type: TransportType;
    currency: Currency;
    price: number;
} {
    return {
        type: from_candid_TransportType_n52(_uploadFile, _downloadFile, value.type),
        currency: value.currency,
        price: value.price
    };
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    cultural: null;
} | {
    historical: null;
} | {
    natural: null;
}): PlaceType {
    return "other" in value ? PlaceType.other : "cultural" in value ? PlaceType.cultural : "historical" in value ? PlaceType.historical : "natural" in value ? PlaceType.natural : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    veg: null;
} | {
    nonVeg: null;
} | {
    other: null;
}): FoodType {
    return "veg" in value ? FoodType.veg : "nonVeg" in value ? FoodType.nonVeg : "other" in value ? FoodType.other : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotel: null;
} | {
    other: null;
} | {
    apartment: null;
} | {
    hostel: null;
}): AccommodationType {
    return "hotel" in value ? AccommodationType.hotel : "other" in value ? AccommodationType.other : "apartment" in value ? AccommodationType.apartment : "hostel" in value ? AccommodationType.hostel : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metro: null;
} | {
    train: null;
} | {
    carRentals: null;
} | {
    other: null;
} | {
    publicBus: null;
} | {
    bikeRentals: null;
} | {
    taxi: null;
} | {
    autoRikshaw: null;
} | {
    taxiService: null;
} | {
    ferry: null;
}): TransportType {
    return "metro" in value ? TransportType.metro : "train" in value ? TransportType.train : "carRentals" in value ? TransportType.carRentals : "other" in value ? TransportType.other : "publicBus" in value ? TransportType.publicBus : "bikeRentals" in value ? TransportType.bikeRentals : "taxi" in value ? TransportType.taxi : "autoRikshaw" in value ? TransportType.autoRikshaw : "taxiService" in value ? TransportType.taxiService : "ferry" in value ? TransportType.ferry : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TripPlan>): Array<TripPlan> {
    return value.map((x)=>from_candid_TripPlan_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToDo>): Array<ToDo> {
    return value.map((x)=>from_candid_ToDo_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MustVisitPlace>): Array<MustVisitPlace> {
    return value.map((x)=>from_candid_MustVisitPlace_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodRecommendation>): Array<FoodRecommendation> {
    return value.map((x)=>from_candid_FoodRecommendation_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Accommodation>): Array<Accommodation> {
    return value.map((x)=>from_candid_Accommodation_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LocalTransportOption>): Array<LocalTransportOption> {
    return value.map((x)=>from_candid_LocalTransportOption_n50(_uploadFile, _downloadFile, x));
}
function to_candid_AccommodationType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccommodationType): _AccommodationType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Accommodation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Accommodation): _Accommodation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_FoodRecommendation_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodRecommendation): _FoodRecommendation {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_FoodType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodType): _FoodType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_LocalTransportOption_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocalTransportOption): _LocalTransportOption {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_MustVisitPlace_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MustVisitPlace): _MustVisitPlace {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceType): _PlaceType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ToDo_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToDo): _ToDo {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_TransportType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransportType): _TransportType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    type: TransportType;
    currency: Currency;
    price: number;
}): {
    type: _TransportType;
    currency: _Currency;
    price: number;
} {
    return {
        type: to_candid_TransportType_n14(_uploadFile, _downloadFile, value.type),
        currency: value.currency,
        price: value.price
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    type: PlaceType;
    description: string;
}): {
    name: string;
    type: _PlaceType;
    description: string;
} {
    return {
        name: value.name,
        type: to_candid_PlaceType_n19(_uploadFile, _downloadFile, value.type),
        description: value.description
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    completed: boolean;
    dueDate?: Time;
    notes: string;
}): {
    title: string;
    completed: boolean;
    dueDate: [] | [_Time];
    notes: string;
} {
    return {
        title: value.title,
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        notes: value.notes
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pricePerNight: number;
    name: string;
    type: AccommodationType;
    location: string;
}): {
    pricePerNight: number;
    name: string;
    type: _AccommodationType;
    location: string;
} {
    return {
        pricePerNight: value.pricePerNight,
        name: value.name,
        type: to_candid_AccommodationType_n4(_uploadFile, _downloadFile, value.type),
        location: value.location
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    type: FoodType;
    description: string;
    budgetLevel: string;
    imageUrl?: string;
    popularity: bigint;
}): {
    name: string;
    type: _FoodType;
    description: string;
    budgetLevel: string;
    imageUrl: [] | [string];
    popularity: bigint;
} {
    return {
        name: value.name,
        type: to_candid_FoodType_n9(_uploadFile, _downloadFile, value.type),
        description: value.description,
        budgetLevel: value.budgetLevel,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        popularity: value.popularity
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodType): {
    veg: null;
} | {
    nonVeg: null;
} | {
    other: null;
} {
    return value == FoodType.veg ? {
        veg: null
    } : value == FoodType.nonVeg ? {
        nonVeg: null
    } : value == FoodType.other ? {
        other: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransportType): {
    metro: null;
} | {
    train: null;
} | {
    carRentals: null;
} | {
    other: null;
} | {
    publicBus: null;
} | {
    bikeRentals: null;
} | {
    taxi: null;
} | {
    autoRikshaw: null;
} | {
    taxiService: null;
} | {
    ferry: null;
} {
    return value == TransportType.metro ? {
        metro: null
    } : value == TransportType.train ? {
        train: null
    } : value == TransportType.carRentals ? {
        carRentals: null
    } : value == TransportType.other ? {
        other: null
    } : value == TransportType.publicBus ? {
        publicBus: null
    } : value == TransportType.bikeRentals ? {
        bikeRentals: null
    } : value == TransportType.taxi ? {
        taxi: null
    } : value == TransportType.autoRikshaw ? {
        autoRikshaw: null
    } : value == TransportType.taxiService ? {
        taxiService: null
    } : value == TransportType.ferry ? {
        ferry: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceType): {
    other: null;
} | {
    cultural: null;
} | {
    historical: null;
} | {
    natural: null;
} {
    return value == PlaceType.other ? {
        other: null
    } : value == PlaceType.cultural ? {
        cultural: null
    } : value == PlaceType.historical ? {
        historical: null
    } : value == PlaceType.natural ? {
        natural: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccommodationType): {
    hotel: null;
} | {
    other: null;
} | {
    apartment: null;
} | {
    hostel: null;
} {
    return value == AccommodationType.hotel ? {
        hotel: null
    } : value == AccommodationType.other ? {
        other: null
    } : value == AccommodationType.apartment ? {
        apartment: null
    } : value == AccommodationType.hostel ? {
        hostel: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Accommodation>): Array<_Accommodation> {
    return value.map((x)=>to_candid_Accommodation_n2(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LocalTransportOption>): Array<_LocalTransportOption> {
    return value.map((x)=>to_candid_LocalTransportOption_n12(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MustVisitPlace>): Array<_MustVisitPlace> {
    return value.map((x)=>to_candid_MustVisitPlace_n17(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ToDo>): Array<_ToDo> {
    return value.map((x)=>to_candid_ToDo_n22(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FoodRecommendation>): Array<_FoodRecommendation> {
    return value.map((x)=>to_candid_FoodRecommendation_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
